# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GTS_mainwindow_vL1_0.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(968, 663)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 310, 711, 321))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(11)
        self.tabWidget.setFont(font)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.grpBox_IMU = QtGui.QGroupBox(self.tab)
        self.grpBox_IMU.setGeometry(QtCore.QRect(10, 0, 411, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.grpBox_IMU.setFont(font)
        self.grpBox_IMU.setObjectName(_fromUtf8("grpBox_IMU"))
        self.cbo_imuComPort = QtGui.QComboBox(self.grpBox_IMU)
        self.cbo_imuComPort.setGeometry(QtCore.QRect(10, 40, 69, 22))
        self.cbo_imuComPort.setMaxVisibleItems(10)
        self.cbo_imuComPort.setObjectName(_fromUtf8("cbo_imuComPort"))
        self.lbl_comPort = QtGui.QLabel(self.grpBox_IMU)
        self.lbl_comPort.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.lbl_comPort.setObjectName(_fromUtf8("lbl_comPort"))
        self.lbl_baudRate = QtGui.QLabel(self.grpBox_IMU)
        self.lbl_baudRate.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.lbl_baudRate.setObjectName(_fromUtf8("lbl_baudRate"))
        self.lbl_pollFreq = QtGui.QLabel(self.grpBox_IMU)
        self.lbl_pollFreq.setGeometry(QtCore.QRect(190, 20, 121, 16))
        self.lbl_pollFreq.setObjectName(_fromUtf8("lbl_pollFreq"))
        self.cbo_imuBaudRate = QtGui.QComboBox(self.grpBox_IMU)
        self.cbo_imuBaudRate.setGeometry(QtCore.QRect(100, 40, 69, 22))
        self.cbo_imuBaudRate.setObjectName(_fromUtf8("cbo_imuBaudRate"))
        self.btn_imuConnect = QtGui.QPushButton(self.grpBox_IMU)
        self.btn_imuConnect.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.btn_imuConnect.setObjectName(_fromUtf8("btn_imuConnect"))
        self.spn_imuPollPeriod = QtGui.QSpinBox(self.grpBox_IMU)
        self.spn_imuPollPeriod.setGeometry(QtCore.QRect(181, 40, 51, 22))
        self.spn_imuPollPeriod.setMinimum(1)
        self.spn_imuPollPeriod.setMaximum(100)
        self.spn_imuPollPeriod.setProperty("value", 10)
        self.spn_imuPollPeriod.setObjectName(_fromUtf8("spn_imuPollPeriod"))
        self.label = QtGui.QLabel(self.grpBox_IMU)
        self.label.setGeometry(QtCore.QRect(240, 40, 81, 16))
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setObjectName(_fromUtf8("label"))
        self.grpBox_IMU_2 = QtGui.QGroupBox(self.tab)
        self.grpBox_IMU_2.setGeometry(QtCore.QRect(10, 80, 411, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.grpBox_IMU_2.setFont(font)
        self.grpBox_IMU_2.setObjectName(_fromUtf8("grpBox_IMU_2"))
        self.cbo_aprsComPort = QtGui.QComboBox(self.grpBox_IMU_2)
        self.cbo_aprsComPort.setGeometry(QtCore.QRect(10, 40, 69, 22))
        self.cbo_aprsComPort.setMaxVisibleItems(10)
        self.cbo_aprsComPort.setObjectName(_fromUtf8("cbo_aprsComPort"))
        self.lbl_comPort_2 = QtGui.QLabel(self.grpBox_IMU_2)
        self.lbl_comPort_2.setGeometry(QtCore.QRect(10, 20, 61, 16))
        self.lbl_comPort_2.setObjectName(_fromUtf8("lbl_comPort_2"))
        self.lbl_baudRate_2 = QtGui.QLabel(self.grpBox_IMU_2)
        self.lbl_baudRate_2.setGeometry(QtCore.QRect(100, 20, 71, 16))
        self.lbl_baudRate_2.setObjectName(_fromUtf8("lbl_baudRate_2"))
        self.lbl_pollFreq_2 = QtGui.QLabel(self.grpBox_IMU_2)
        self.lbl_pollFreq_2.setGeometry(QtCore.QRect(190, 20, 121, 16))
        self.lbl_pollFreq_2.setObjectName(_fromUtf8("lbl_pollFreq_2"))
        self.cbo_aprsBaudRate = QtGui.QComboBox(self.grpBox_IMU_2)
        self.cbo_aprsBaudRate.setGeometry(QtCore.QRect(100, 40, 69, 22))
        self.cbo_aprsBaudRate.setObjectName(_fromUtf8("cbo_aprsBaudRate"))
        self.btn_aprsConnect = QtGui.QPushButton(self.grpBox_IMU_2)
        self.btn_aprsConnect.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.btn_aprsConnect.setObjectName(_fromUtf8("btn_aprsConnect"))
        self.spn_aprsPollPeriod = QtGui.QSpinBox(self.grpBox_IMU_2)
        self.spn_aprsPollPeriod.setGeometry(QtCore.QRect(181, 40, 51, 22))
        self.spn_aprsPollPeriod.setMinimum(1)
        self.spn_aprsPollPeriod.setMaximum(100)
        self.spn_aprsPollPeriod.setProperty("value", 10)
        self.spn_aprsPollPeriod.setObjectName(_fromUtf8("spn_aprsPollPeriod"))
        self.label_2 = QtGui.QLabel(self.grpBox_IMU_2)
        self.label_2.setGeometry(QtCore.QRect(240, 40, 81, 16))
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.grpBox_IMU_3 = QtGui.QGroupBox(self.tab)
        self.grpBox_IMU_3.setGeometry(QtCore.QRect(10, 160, 411, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.grpBox_IMU_3.setFont(font)
        self.grpBox_IMU_3.setObjectName(_fromUtf8("grpBox_IMU_3"))
        self.cbo_srvoComPort = QtGui.QComboBox(self.grpBox_IMU_3)
        self.cbo_srvoComPort.setGeometry(QtCore.QRect(10, 40, 69, 22))
        self.cbo_srvoComPort.setMaxVisibleItems(10)
        self.cbo_srvoComPort.setObjectName(_fromUtf8("cbo_srvoComPort"))
        self.lbl_comPort_3 = QtGui.QLabel(self.grpBox_IMU_3)
        self.lbl_comPort_3.setGeometry(QtCore.QRect(10, 20, 71, 16))
        self.lbl_comPort_3.setObjectName(_fromUtf8("lbl_comPort_3"))
        self.lbl_baudRate_3 = QtGui.QLabel(self.grpBox_IMU_3)
        self.lbl_baudRate_3.setGeometry(QtCore.QRect(100, 20, 81, 16))
        self.lbl_baudRate_3.setObjectName(_fromUtf8("lbl_baudRate_3"))
        self.lbl_pollFreq_3 = QtGui.QLabel(self.grpBox_IMU_3)
        self.lbl_pollFreq_3.setGeometry(QtCore.QRect(190, 20, 121, 16))
        self.lbl_pollFreq_3.setObjectName(_fromUtf8("lbl_pollFreq_3"))
        self.cbo_srvoBaudRate = QtGui.QComboBox(self.grpBox_IMU_3)
        self.cbo_srvoBaudRate.setGeometry(QtCore.QRect(100, 40, 69, 22))
        self.cbo_srvoBaudRate.setObjectName(_fromUtf8("cbo_srvoBaudRate"))
        self.btn_srvoConnect = QtGui.QPushButton(self.grpBox_IMU_3)
        self.btn_srvoConnect.setGeometry(QtCore.QRect(330, 40, 75, 23))
        self.btn_srvoConnect.setObjectName(_fromUtf8("btn_srvoConnect"))
        self.spn_srvoPollPeriod = QtGui.QSpinBox(self.grpBox_IMU_3)
        self.spn_srvoPollPeriod.setGeometry(QtCore.QRect(181, 40, 51, 22))
        self.spn_srvoPollPeriod.setMinimum(1)
        self.spn_srvoPollPeriod.setMaximum(100)
        self.spn_srvoPollPeriod.setProperty("value", 10)
        self.spn_srvoPollPeriod.setObjectName(_fromUtf8("spn_srvoPollPeriod"))
        self.label_3 = QtGui.QLabel(self.grpBox_IMU_3)
        self.label_3.setGeometry(QtCore.QRect(240, 40, 81, 16))
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btn_saveSettings = QtGui.QPushButton(self.tab)
        self.btn_saveSettings.setGeometry(QtCore.QRect(290, 280, 101, 23))
        self.btn_saveSettings.setObjectName(_fromUtf8("btn_saveSettings"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.groupBox = QtGui.QGroupBox(self.tab_3)
        self.groupBox.setGeometry(QtCore.QRect(10, 0, 671, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.txt_logData = QtGui.QTextBrowser(self.groupBox)
        self.txt_logData.setGeometry(QtCore.QRect(130, 20, 531, 281))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(8)
        self.txt_logData.setFont(font)
        self.txt_logData.setObjectName(_fromUtf8("txt_logData"))
        self.chkBox_logIMU = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logIMU.setGeometry(QtCore.QRect(10, 30, 91, 17))
        self.chkBox_logIMU.setChecked(True)
        self.chkBox_logIMU.setObjectName(_fromUtf8("chkBox_logIMU"))
        self.chkBox_logInfo = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logInfo.setGeometry(QtCore.QRect(10, 90, 70, 17))
        self.chkBox_logInfo.setChecked(True)
        self.chkBox_logInfo.setObjectName(_fromUtf8("chkBox_logInfo"))
        self.chkBox_logWarning = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logWarning.setGeometry(QtCore.QRect(10, 120, 81, 17))
        self.chkBox_logWarning.setChecked(True)
        self.chkBox_logWarning.setObjectName(_fromUtf8("chkBox_logWarning"))
        self.chkBox_logError = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logError.setGeometry(QtCore.QRect(10, 150, 70, 17))
        self.chkBox_logError.setChecked(True)
        self.chkBox_logError.setObjectName(_fromUtf8("chkBox_logError"))
        self.chkBox_logSevere = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logSevere.setGeometry(QtCore.QRect(10, 180, 70, 17))
        self.chkBox_logSevere.setChecked(True)
        self.chkBox_logSevere.setObjectName(_fromUtf8("chkBox_logSevere"))
        self.chkBox_logFatal = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logFatal.setGeometry(QtCore.QRect(10, 210, 70, 17))
        self.chkBox_logFatal.setChecked(True)
        self.chkBox_logFatal.setObjectName(_fromUtf8("chkBox_logFatal"))
        self.chkBox_logAPRS = QtGui.QCheckBox(self.groupBox)
        self.chkBox_logAPRS.setGeometry(QtCore.QRect(10, 60, 101, 17))
        self.chkBox_logAPRS.setChecked(True)
        self.chkBox_logAPRS.setObjectName(_fromUtf8("chkBox_logAPRS"))
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 0, 201, 301))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.txt_sttnAziCalibrationTable = QtGui.QTextBrowser(self.groupBox_9)
        self.txt_sttnAziCalibrationTable.setGeometry(QtCore.QRect(10, 20, 181, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_sttnAziCalibrationTable.setFont(font)
        self.txt_sttnAziCalibrationTable.setObjectName(_fromUtf8("txt_sttnAziCalibrationTable"))
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setGeometry(QtCore.QRect(210, 0, 201, 301))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.txt_sttnElevCalibrationTable = QtGui.QTextBrowser(self.groupBox_10)
        self.txt_sttnElevCalibrationTable.setGeometry(QtCore.QRect(10, 20, 181, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_sttnElevCalibrationTable.setFont(font)
        self.txt_sttnElevCalibrationTable.setObjectName(_fromUtf8("txt_sttnElevCalibrationTable"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 0, 231, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lcd_trgtTimestamp = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtTimestamp.setGeometry(QtCore.QRect(120, 30, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_trgtTimestamp.setFont(font)
        self.lcd_trgtTimestamp.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtTimestamp.setNumDigits(8)
        self.lcd_trgtTimestamp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtTimestamp.setObjectName(_fromUtf8("lcd_trgtTimestamp"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lcd_trgtLatitude = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtLatitude.setGeometry(QtCore.QRect(120, 60, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_trgtLatitude.setFont(font)
        self.lcd_trgtLatitude.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtLatitude.setNumDigits(8)
        self.lcd_trgtLatitude.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtLatitude.setObjectName(_fromUtf8("lcd_trgtLatitude"))
        self.lcd_trgtLongitude = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtLongitude.setGeometry(QtCore.QRect(120, 90, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_trgtLongitude.setFont(font)
        self.lcd_trgtLongitude.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtLongitude.setDigitCount(8)
        self.lcd_trgtLongitude.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtLongitude.setObjectName(_fromUtf8("lcd_trgtLongitude"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.lcd_trgtAltitude = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtAltitude.setGeometry(QtCore.QRect(120, 120, 101, 23))
        self.lcd_trgtAltitude.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtAltitude.setNumDigits(8)
        self.lcd_trgtAltitude.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtAltitude.setObjectName(_fromUtf8("lcd_trgtAltitude"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.lcd_trgtBearing = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtBearing.setGeometry(QtCore.QRect(120, 150, 101, 23))
        self.lcd_trgtBearing.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtBearing.setNumDigits(8)
        self.lcd_trgtBearing.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtBearing.setObjectName(_fromUtf8("lcd_trgtBearing"))
        self.lcd_trgtElevation = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtElevation.setGeometry(QtCore.QRect(120, 180, 101, 23))
        self.lcd_trgtElevation.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtElevation.setNumDigits(8)
        self.lcd_trgtElevation.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtElevation.setObjectName(_fromUtf8("lcd_trgtElevation"))
        self.lcd_trgtDistance = QtGui.QLCDNumber(self.groupBox_2)
        self.lcd_trgtDistance.setGeometry(QtCore.QRect(120, 210, 101, 23))
        self.lcd_trgtDistance.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_trgtDistance.setNumDigits(8)
        self.lcd_trgtDistance.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_trgtDistance.setObjectName(_fromUtf8("lcd_trgtDistance"))
        self.label_24 = QtGui.QLabel(self.groupBox_2)
        self.label_24.setGeometry(QtCore.QRect(10, 210, 101, 16))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.cbo_trgtDataSource = QtGui.QComboBox(self.groupBox_2)
        self.cbo_trgtDataSource.setGeometry(QtCore.QRect(10, 270, 101, 22))
        self.cbo_trgtDataSource.setObjectName(_fromUtf8("cbo_trgtDataSource"))
        self.lbl_comPort_4 = QtGui.QLabel(self.groupBox_2)
        self.lbl_comPort_4.setGeometry(QtCore.QRect(10, 250, 101, 16))
        self.lbl_comPort_4.setObjectName(_fromUtf8("lbl_comPort_4"))
        self.line = QtGui.QFrame(self.groupBox_2)
        self.line.setGeometry(QtCore.QRect(7, 230, 211, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.btn_trgtClearSources = QtGui.QPushButton(self.groupBox_2)
        self.btn_trgtClearSources.setGeometry(QtCore.QRect(120, 270, 101, 23))
        self.btn_trgtClearSources.setObjectName(_fromUtf8("btn_trgtClearSources"))
        self.groupBox_3 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(250, 0, 231, 311))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_12 = QtGui.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.lcd_sttnTimestamp = QtGui.QLCDNumber(self.groupBox_3)
        self.lcd_sttnTimestamp.setGeometry(QtCore.QRect(120, 30, 101, 23))
        self.lcd_sttnTimestamp.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnTimestamp.setLineWidth(1)
        self.lcd_sttnTimestamp.setNumDigits(8)
        self.lcd_sttnTimestamp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnTimestamp.setObjectName(_fromUtf8("lcd_sttnTimestamp"))
        self.label_13 = QtGui.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.lcd_sttnLatitude = QtGui.QLCDNumber(self.groupBox_3)
        self.lcd_sttnLatitude.setGeometry(QtCore.QRect(120, 60, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnLatitude.setFont(font)
        self.lcd_sttnLatitude.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnLatitude.setNumDigits(8)
        self.lcd_sttnLatitude.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnLatitude.setObjectName(_fromUtf8("lcd_sttnLatitude"))
        self.lcd_sttnLongitude = QtGui.QLCDNumber(self.groupBox_3)
        self.lcd_sttnLongitude.setGeometry(QtCore.QRect(120, 90, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnLongitude.setFont(font)
        self.lcd_sttnLongitude.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnLongitude.setNumDigits(8)
        self.lcd_sttnLongitude.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnLongitude.setObjectName(_fromUtf8("lcd_sttnLongitude"))
        self.label_15 = QtGui.QLabel(self.groupBox_3)
        self.label_15.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.lcd_sttnAltitude = QtGui.QLCDNumber(self.groupBox_3)
        self.lcd_sttnAltitude.setGeometry(QtCore.QRect(120, 120, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnAltitude.setFont(font)
        self.lcd_sttnAltitude.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnAltitude.setNumDigits(8)
        self.lcd_sttnAltitude.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnAltitude.setObjectName(_fromUtf8("lcd_sttnAltitude"))
        self.label_16 = QtGui.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(10, 150, 111, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.groupBox_3)
        self.label_17.setGeometry(QtCore.QRect(10, 180, 101, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.lcd_sttnLock = QtGui.QLCDNumber(self.groupBox_3)
        self.lcd_sttnLock.setGeometry(QtCore.QRect(120, 150, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnLock.setFont(font)
        self.lcd_sttnLock.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnLock.setNumDigits(8)
        self.lcd_sttnLock.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnLock.setObjectName(_fromUtf8("lcd_sttnLock"))
        self.lcd_sttnSatelliteCount = QtGui.QLCDNumber(self.groupBox_3)
        self.lcd_sttnSatelliteCount.setGeometry(QtCore.QRect(120, 180, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnSatelliteCount.setFont(font)
        self.lcd_sttnSatelliteCount.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnSatelliteCount.setNumDigits(8)
        self.lcd_sttnSatelliteCount.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnSatelliteCount.setObjectName(_fromUtf8("lcd_sttnSatelliteCount"))
        self.cbo_sttnUpdateMethod = QtGui.QComboBox(self.groupBox_3)
        self.cbo_sttnUpdateMethod.setGeometry(QtCore.QRect(10, 240, 111, 22))
        self.cbo_sttnUpdateMethod.setObjectName(_fromUtf8("cbo_sttnUpdateMethod"))
        self.lbl_comPort_5 = QtGui.QLabel(self.groupBox_3)
        self.lbl_comPort_5.setGeometry(QtCore.QRect(10, 220, 71, 16))
        self.lbl_comPort_5.setObjectName(_fromUtf8("lbl_comPort_5"))
        self.line_2 = QtGui.QFrame(self.groupBox_3)
        self.line_2.setGeometry(QtCore.QRect(10, 200, 211, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.lbl_comPort_6 = QtGui.QLabel(self.groupBox_3)
        self.lbl_comPort_6.setGeometry(QtCore.QRect(130, 220, 121, 16))
        self.lbl_comPort_6.setObjectName(_fromUtf8("lbl_comPort_6"))
        self.spn_sttnUpdatePeriod = QtGui.QSpinBox(self.groupBox_3)
        self.spn_sttnUpdatePeriod.setGeometry(QtCore.QRect(130, 240, 91, 22))
        self.spn_sttnUpdatePeriod.setMinimum(1)
        self.spn_sttnUpdatePeriod.setMaximum(1000)
        self.spn_sttnUpdatePeriod.setProperty("value", 10)
        self.spn_sttnUpdatePeriod.setObjectName(_fromUtf8("spn_sttnUpdatePeriod"))
        self.btn_sttnUpdatePosition = QtGui.QPushButton(self.groupBox_3)
        self.btn_sttnUpdatePosition.setGeometry(QtCore.QRect(40, 270, 151, 23))
        self.btn_sttnUpdatePosition.setObjectName(_fromUtf8("btn_sttnUpdatePosition"))
        self.groupBox_4 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(730, 0, 231, 201))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.lcd_sttnPointingTimestamp = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnPointingTimestamp.setGeometry(QtCore.QRect(120, 30, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnPointingTimestamp.setFont(font)
        self.lcd_sttnPointingTimestamp.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnPointingTimestamp.setNumDigits(8)
        self.lcd_sttnPointingTimestamp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnPointingTimestamp.setObjectName(_fromUtf8("lcd_sttnPointingTimestamp"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lcd_sttnBearing = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnBearing.setGeometry(QtCore.QRect(120, 60, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnBearing.setFont(font)
        self.lcd_sttnBearing.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnBearing.setNumDigits(8)
        self.lcd_sttnBearing.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnBearing.setObjectName(_fromUtf8("lcd_sttnBearing"))
        self.lcd_sttnElevation = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnElevation.setGeometry(QtCore.QRect(120, 90, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnElevation.setFont(font)
        self.lcd_sttnElevation.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnElevation.setDigitCount(8)
        self.lcd_sttnElevation.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnElevation.setObjectName(_fromUtf8("lcd_sttnElevation"))
        self.lcd_sttnLevel = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnLevel.setGeometry(QtCore.QRect(120, 120, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnLevel.setFont(font)
        self.lcd_sttnLevel.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnLevel.setDigitCount(8)
        self.lcd_sttnLevel.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnLevel.setObjectName(_fromUtf8("lcd_sttnLevel"))
        self.label_31 = QtGui.QLabel(self.groupBox_4)
        self.label_31.setGeometry(QtCore.QRect(10, 120, 81, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.lcd_sttnSysCalibration = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnSysCalibration.setGeometry(QtCore.QRect(70, 170, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnSysCalibration.setFont(font)
        self.lcd_sttnSysCalibration.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnSysCalibration.setDigitCount(3)
        self.lcd_sttnSysCalibration.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnSysCalibration.setObjectName(_fromUtf8("lcd_sttnSysCalibration"))
        self.lcd_sttnGyroCalibration = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnGyroCalibration.setGeometry(QtCore.QRect(110, 170, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnGyroCalibration.setFont(font)
        self.lcd_sttnGyroCalibration.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnGyroCalibration.setDigitCount(3)
        self.lcd_sttnGyroCalibration.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnGyroCalibration.setObjectName(_fromUtf8("lcd_sttnGyroCalibration"))
        self.lcd_sttnAcclCalibration = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnAcclCalibration.setGeometry(QtCore.QRect(150, 170, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnAcclCalibration.setFont(font)
        self.lcd_sttnAcclCalibration.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnAcclCalibration.setDigitCount(3)
        self.lcd_sttnAcclCalibration.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnAcclCalibration.setObjectName(_fromUtf8("lcd_sttnAcclCalibration"))
        self.lcd_sttnMagCalibration = QtGui.QLCDNumber(self.groupBox_4)
        self.lcd_sttnMagCalibration.setGeometry(QtCore.QRect(190, 170, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnMagCalibration.setFont(font)
        self.lcd_sttnMagCalibration.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnMagCalibration.setDigitCount(3)
        self.lcd_sttnMagCalibration.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnMagCalibration.setObjectName(_fromUtf8("lcd_sttnMagCalibration"))
        self.lbl_comPort_7 = QtGui.QLabel(self.groupBox_4)
        self.lbl_comPort_7.setGeometry(QtCore.QRect(70, 150, 21, 16))
        self.lbl_comPort_7.setObjectName(_fromUtf8("lbl_comPort_7"))
        self.lbl_comPort_8 = QtGui.QLabel(self.groupBox_4)
        self.lbl_comPort_8.setGeometry(QtCore.QRect(110, 150, 31, 16))
        self.lbl_comPort_8.setObjectName(_fromUtf8("lbl_comPort_8"))
        self.lbl_comPort_9 = QtGui.QLabel(self.groupBox_4)
        self.lbl_comPort_9.setGeometry(QtCore.QRect(150, 150, 31, 16))
        self.lbl_comPort_9.setObjectName(_fromUtf8("lbl_comPort_9"))
        self.lbl_comPort_10 = QtGui.QLabel(self.groupBox_4)
        self.lbl_comPort_10.setGeometry(QtCore.QRect(190, 150, 31, 16))
        self.lbl_comPort_10.setObjectName(_fromUtf8("lbl_comPort_10"))
        self.label_35 = QtGui.QLabel(self.groupBox_4)
        self.label_35.setGeometry(QtCore.QRect(10, 160, 41, 16))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_5.setGeometry(QtCore.QRect(490, 0, 231, 251))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_28 = QtGui.QLabel(self.groupBox_5)
        self.label_28.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lcd_sttnOffsetTimestamp = QtGui.QLCDNumber(self.groupBox_5)
        self.lcd_sttnOffsetTimestamp.setGeometry(QtCore.QRect(120, 30, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnOffsetTimestamp.setFont(font)
        self.lcd_sttnOffsetTimestamp.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnOffsetTimestamp.setNumDigits(8)
        self.lcd_sttnOffsetTimestamp.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnOffsetTimestamp.setObjectName(_fromUtf8("lcd_sttnOffsetTimestamp"))
        self.label_29 = QtGui.QLabel(self.groupBox_5)
        self.label_29.setGeometry(QtCore.QRect(10, 60, 111, 16))
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.label_30 = QtGui.QLabel(self.groupBox_5)
        self.label_30.setGeometry(QtCore.QRect(10, 150, 101, 16))
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.lcd_sttnCenterBearing = QtGui.QLCDNumber(self.groupBox_5)
        self.lcd_sttnCenterBearing.setGeometry(QtCore.QRect(120, 60, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnCenterBearing.setFont(font)
        self.lcd_sttnCenterBearing.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnCenterBearing.setNumDigits(8)
        self.lcd_sttnCenterBearing.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnCenterBearing.setObjectName(_fromUtf8("lcd_sttnCenterBearing"))
        self.lcd_sttnAppliedElevation = QtGui.QLCDNumber(self.groupBox_5)
        self.lcd_sttnAppliedElevation.setGeometry(QtCore.QRect(120, 150, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnAppliedElevation.setFont(font)
        self.lcd_sttnAppliedElevation.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnAppliedElevation.setDigitCount(8)
        self.lcd_sttnAppliedElevation.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnAppliedElevation.setObjectName(_fromUtf8("lcd_sttnAppliedElevation"))
        self.label_32 = QtGui.QLabel(self.groupBox_5)
        self.label_32.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.lcd_sttnAppliedBearing = QtGui.QLCDNumber(self.groupBox_5)
        self.lcd_sttnAppliedBearing.setGeometry(QtCore.QRect(120, 90, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnAppliedBearing.setFont(font)
        self.lcd_sttnAppliedBearing.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnAppliedBearing.setNumDigits(8)
        self.lcd_sttnAppliedBearing.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnAppliedBearing.setObjectName(_fromUtf8("lcd_sttnAppliedBearing"))
        self.lcd_sttnCenterElevation = QtGui.QLCDNumber(self.groupBox_5)
        self.lcd_sttnCenterElevation.setGeometry(QtCore.QRect(120, 120, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnCenterElevation.setFont(font)
        self.lcd_sttnCenterElevation.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnCenterElevation.setDigitCount(8)
        self.lcd_sttnCenterElevation.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnCenterElevation.setObjectName(_fromUtf8("lcd_sttnCenterElevation"))
        self.label_33 = QtGui.QLabel(self.groupBox_5)
        self.label_33.setGeometry(QtCore.QRect(10, 120, 101, 16))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.line_3 = QtGui.QFrame(self.groupBox_5)
        self.line_3.setGeometry(QtCore.QRect(10, 200, 211, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.btn_sttnUpdatePointing = QtGui.QPushButton(self.groupBox_5)
        self.btn_sttnUpdatePointing.setGeometry(QtCore.QRect(40, 220, 151, 23))
        self.btn_sttnUpdatePointing.setObjectName(_fromUtf8("btn_sttnUpdatePointing"))
        self.lcd_sttnCenterLevel = QtGui.QLCDNumber(self.groupBox_5)
        self.lcd_sttnCenterLevel.setGeometry(QtCore.QRect(120, 180, 101, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Shell Dlg 2"))
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcd_sttnCenterLevel.setFont(font)
        self.lcd_sttnCenterLevel.setStyleSheet(_fromUtf8("QLCDNumber{\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    color: rgb(20, 200, 2);    \n"
"    background-color: rgb2(0, 0, 0);\n"
"}"))
        self.lcd_sttnCenterLevel.setDigitCount(8)
        self.lcd_sttnCenterLevel.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_sttnCenterLevel.setObjectName(_fromUtf8("lcd_sttnCenterLevel"))
        self.label_34 = QtGui.QLabel(self.groupBox_5)
        self.label_34.setGeometry(QtCore.QRect(10, 180, 101, 16))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.groupBox_6 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_6.setGeometry(QtCore.QRect(730, 200, 231, 421))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_8.setGeometry(QtCore.QRect(10, 30, 211, 121))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.btn_moveCenter = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveCenter.setGeometry(QtCore.QRect(80, 60, 61, 23))
        self.btn_moveCenter.setObjectName(_fromUtf8("btn_moveCenter"))
        self.btn_moveUp = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveUp.setGeometry(QtCore.QRect(60, 30, 51, 23))
        self.btn_moveUp.setObjectName(_fromUtf8("btn_moveUp"))
        self.btn_moveDown = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveDown.setGeometry(QtCore.QRect(60, 90, 51, 23))
        self.btn_moveDown.setObjectName(_fromUtf8("btn_moveDown"))
        self.btn_moveLeft = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveLeft.setGeometry(QtCore.QRect(10, 60, 31, 23))
        self.btn_moveLeft.setObjectName(_fromUtf8("btn_moveLeft"))
        self.btn_moveLeftFine = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveLeftFine.setGeometry(QtCore.QRect(40, 60, 31, 23))
        self.btn_moveLeftFine.setObjectName(_fromUtf8("btn_moveLeftFine"))
        self.btn_moveRight = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveRight.setGeometry(QtCore.QRect(180, 60, 31, 23))
        self.btn_moveRight.setObjectName(_fromUtf8("btn_moveRight"))
        self.btn_moveRightFine = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveRightFine.setGeometry(QtCore.QRect(150, 60, 31, 23))
        self.btn_moveRightFine.setObjectName(_fromUtf8("btn_moveRightFine"))
        self.btn_moveUpFine = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveUpFine.setGeometry(QtCore.QRect(110, 30, 51, 23))
        self.btn_moveUpFine.setObjectName(_fromUtf8("btn_moveUpFine"))
        self.btn_moveDownFine = QtGui.QPushButton(self.groupBox_8)
        self.btn_moveDownFine.setGeometry(QtCore.QRect(110, 90, 51, 23))
        self.btn_moveDownFine.setObjectName(_fromUtf8("btn_moveDownFine"))
        self.groupBox_7 = QtGui.QGroupBox(self.groupBox_6)
        self.groupBox_7.setGeometry(QtCore.QRect(10, 160, 211, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.spn_moveSensitivity = QtGui.QSpinBox(self.groupBox_7)
        self.spn_moveSensitivity.setGeometry(QtCore.QRect(10, 30, 51, 22))
        self.spn_moveSensitivity.setMinimum(1)
        self.spn_moveSensitivity.setMaximum(10)
        self.spn_moveSensitivity.setObjectName(_fromUtf8("spn_moveSensitivity"))
        self.lbl_comPort_12 = QtGui.QLabel(self.groupBox_7)
        self.lbl_comPort_12.setGeometry(QtCore.QRect(70, 30, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Calibri"))
        font.setPointSize(10)
        self.lbl_comPort_12.setFont(font)
        self.lbl_comPort_12.setObjectName(_fromUtf8("lbl_comPort_12"))
        self.btn_sttnCalibrate = QtGui.QPushButton(self.groupBox_6)
        self.btn_sttnCalibrate.setGeometry(QtCore.QRect(30, 230, 171, 23))
        self.btn_sttnCalibrate.setObjectName(_fromUtf8("btn_sttnCalibrate"))
        self.btn_sttnCalibrateIMU = QtGui.QPushButton(self.groupBox_6)
        self.btn_sttnCalibrateIMU.setGeometry(QtCore.QRect(30, 290, 171, 23))
        self.btn_sttnCalibrateIMU.setObjectName(_fromUtf8("btn_sttnCalibrateIMU"))
        self.btn_sttnTrackOn = QtGui.QPushButton(self.groupBox_6)
        self.btn_sttnTrackOn.setGeometry(QtCore.QRect(30, 360, 171, 23))
        self.btn_sttnTrackOn.setObjectName(_fromUtf8("btn_sttnTrackOn"))
        self.line_4 = QtGui.QFrame(self.groupBox_6)
        self.line_4.setGeometry(QtCore.QRect(10, 340, 211, 20))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.prg_sttnCalibrate = QtGui.QProgressBar(self.groupBox_6)
        self.prg_sttnCalibrate.setGeometry(QtCore.QRect(30, 260, 171, 23))
        self.prg_sttnCalibrate.setProperty("value", 0)
        self.prg_sttnCalibrate.setObjectName(_fromUtf8("prg_sttnCalibrate"))
        self.prg_sttnCalibrateIMU = QtGui.QProgressBar(self.groupBox_6)
        self.prg_sttnCalibrateIMU.setGeometry(QtCore.QRect(30, 320, 171, 23))
        self.prg_sttnCalibrateIMU.setProperty("value", 0)
        self.prg_sttnCalibrateIMU.setObjectName(_fromUtf8("prg_sttnCalibrateIMU"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 968, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ground Targeting System", None))
        self.grpBox_IMU.setTitle(_translate("MainWindow", "IMU Connection", None))
        self.lbl_comPort.setText(_translate("MainWindow", "COM Port", None))
        self.lbl_baudRate.setText(_translate("MainWindow", "Baud Rate", None))
        self.lbl_pollFreq.setText(_translate("MainWindow", "Polling Period", None))
        self.btn_imuConnect.setText(_translate("MainWindow", "Connect", None))
        self.label.setText(_translate("MainWindow", "decisecond", None))
        self.grpBox_IMU_2.setTitle(_translate("MainWindow", "APRS Connection", None))
        self.lbl_comPort_2.setText(_translate("MainWindow", "COM Port", None))
        self.lbl_baudRate_2.setText(_translate("MainWindow", "Baud Rate", None))
        self.lbl_pollFreq_2.setText(_translate("MainWindow", "Polling Period", None))
        self.btn_aprsConnect.setText(_translate("MainWindow", "Connect", None))
        self.label_2.setText(_translate("MainWindow", "decisecond", None))
        self.grpBox_IMU_3.setTitle(_translate("MainWindow", "Servo Connection", None))
        self.lbl_comPort_3.setText(_translate("MainWindow", "COM Port", None))
        self.lbl_baudRate_3.setText(_translate("MainWindow", "Baud Rate", None))
        self.lbl_pollFreq_3.setText(_translate("MainWindow", "Polling Period", None))
        self.btn_srvoConnect.setText(_translate("MainWindow", "Connect", None))
        self.label_3.setText(_translate("MainWindow", "decisecond", None))
        self.btn_saveSettings.setText(_translate("MainWindow", "Save Settings", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Settings", None))
        self.groupBox.setTitle(_translate("MainWindow", "Log", None))
        self.chkBox_logIMU.setText(_translate("MainWindow", "Raw IMU", None))
        self.chkBox_logInfo.setText(_translate("MainWindow", "Info", None))
        self.chkBox_logWarning.setText(_translate("MainWindow", "Warning", None))
        self.chkBox_logError.setText(_translate("MainWindow", "Error", None))
        self.chkBox_logSevere.setText(_translate("MainWindow", "Severe", None))
        self.chkBox_logFatal.setText(_translate("MainWindow", "Fatal", None))
        self.chkBox_logAPRS.setText(_translate("MainWindow", "Raw APRS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Log", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "Azimuth Deg. to Steps", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "Elevation Deg. to Steps", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Cal Tables", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Target Position", None))
        self.label_4.setText(_translate("MainWindow", "Timestamp", None))
        self.label_5.setText(_translate("MainWindow", "Latitude", None))
        self.label_6.setText(_translate("MainWindow", "Longitude", None))
        self.label_7.setText(_translate("MainWindow", "Altitude", None))
        self.label_19.setText(_translate("MainWindow", "Azimuth (N)", None))
        self.label_20.setText(_translate("MainWindow", "Elevation", None))
        self.label_24.setText(_translate("MainWindow", "Distance (km)", None))
        self.lbl_comPort_4.setText(_translate("MainWindow", "Data Source(s)", None))
        self.btn_trgtClearSources.setText(_translate("MainWindow", "Clear Sources", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Station Position", None))
        self.label_12.setText(_translate("MainWindow", "Timestamp", None))
        self.label_13.setText(_translate("MainWindow", "Latitude", None))
        self.label_14.setText(_translate("MainWindow", "Longitude", None))
        self.label_15.setText(_translate("MainWindow", "Altitude", None))
        self.label_16.setText(_translate("MainWindow", "Satellite Lock", None))
        self.label_17.setText(_translate("MainWindow", "Satellite Count", None))
        self.lbl_comPort_5.setText(_translate("MainWindow", "Method", None))
        self.lbl_comPort_6.setText(_translate("MainWindow", " Period (dsecs)", None))
        self.btn_sttnUpdatePosition.setText(_translate("MainWindow", "Update Position", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Antenna Pointing", None))
        self.label_21.setText(_translate("MainWindow", "Timestamp", None))
        self.label_22.setText(_translate("MainWindow", "Azimuth (N)", None))
        self.label_23.setText(_translate("MainWindow", "Elevation", None))
        self.label_31.setText(_translate("MainWindow", "Level", None))
        self.lbl_comPort_7.setText(_translate("MainWindow", "Sys", None))
        self.lbl_comPort_8.setText(_translate("MainWindow", "Gyro", None))
        self.lbl_comPort_9.setText(_translate("MainWindow", "Accl", None))
        self.lbl_comPort_10.setText(_translate("MainWindow", "Mag", None))
        self.label_35.setText(_translate("MainWindow", "Calib.", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Pointing Offset", None))
        self.label_28.setText(_translate("MainWindow", "Timestamp", None))
        self.label_29.setText(_translate("MainWindow", "Center Azimuth", None))
        self.label_30.setText(_translate("MainWindow", "Applied Elev.", None))
        self.label_32.setText(_translate("MainWindow", "Applied Azimuth", None))
        self.label_33.setText(_translate("MainWindow", "Center Elev.", None))
        self.btn_sttnUpdatePointing.setText(_translate("MainWindow", "Update Offset", None))
        self.label_34.setText(_translate("MainWindow", "Center Level", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Ground Station Control Panel", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "Manual Pointing", None))
        self.btn_moveCenter.setText(_translate("MainWindow", "Center", None))
        self.btn_moveUp.setText(_translate("MainWindow", "Up", None))
        self.btn_moveDown.setText(_translate("MainWindow", "Dwn", None))
        self.btn_moveLeft.setText(_translate("MainWindow", "<<", None))
        self.btn_moveLeftFine.setText(_translate("MainWindow", "<", None))
        self.btn_moveRight.setText(_translate("MainWindow", ">>", None))
        self.btn_moveRightFine.setText(_translate("MainWindow", ">", None))
        self.btn_moveUpFine.setText(_translate("MainWindow", "Up.f", None))
        self.btn_moveDownFine.setText(_translate("MainWindow", "Dwn.f", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Manual Pointing Sensitivity", None))
        self.lbl_comPort_12.setText(_translate("MainWindow", "servo step(s), Course=5X", None))
        self.btn_sttnCalibrate.setText(_translate("MainWindow", "Calibrate Station", None))
        self.btn_sttnCalibrateIMU.setText(_translate("MainWindow", "Calibrate IMU", None))
        self.btn_sttnTrackOn.setText(_translate("MainWindow", "Tracking ON", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

